# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171027_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='validate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='show_post',
            field=models.BooleanField(default=True),
        ),
    ]
