# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20171030_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='validate',
            new_name='validated',
        ),
        migrations.AlterField(
            model_name='post',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
