# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20171030_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_post_page', models.IntegerField(default=5)),
                ('message', models.TextField(default='')),
                ('recent_posts', models.BooleanField(default=True)),
                ('most_used_tags', models.BooleanField(default=True)),
            ],
        ),
    ]
