# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
