# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20171114_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='nb_post_page',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
